### ISSUE TITLE
XSLT

### ISSUE THREAD

**Issue by JakeCode121** [JakeCode121/Washington_Trail#17]
Hello @haggis78 

I worked on my XSLT with @Bennediction and I wasn't able to get it push through.  I have green on both documents, but it is not running.

Ben provided the opportunity for all of us to link up during office hours, today.
Thanks for you help/

Sincerely,

@JakeCode121

**Comment by cozyycoding** [comment]
Hey @JakeCode121 , 

messed around with the code some and got it working. Turns out we didn't have ```<xsl:apply-templates>``` in the initial file match. Since we're making a list too, the initial HTML should have a select attribute on it so we don't put out the text of the entire document. We also want the ```<ul>``` element to be inside the initial template match. Thus, the body elements of the initial template should look something like this:

```
            <body>
                <ul>
                <xsl:apply-templates select="descendant::place[@placeType='city']"/>
                </ul>    
            </body>
```
Then all we need to do is put the ```<li>``` element around the values of the table. To do this, we just want the ```<li>``` element to surround the ```<xml:value-of>``` elements. We also want to select the text of the element. to do this, we want to do the following 
```
    <xsl:template match="place[@placeType ='city']">

            <li>    <xsl:value-of select= "@text"/></li>

    </xsl:template>
```
Thus, we avoid making the extra ```<ul>``` elements and pull out only the text we want. Hope this helps! Let me know if you still run into problems after this or if anything is unclear or confusing.
