### ISSUE TITLE
Briefing on Tuesday...

### ISSUE THREAD

**Issue by JakeCode121** [JakeCode121/Washington_Trail#31]
Hello all.

I hope everyone had a good thanksgiving.

I'm proposing the following plan for our briefing.

@JakeCode121 will brief the overall concept and the reasoning behind the website.

@dsl28 discuss the xml mark up and the Journal page; how you removed glitches; and how you were able to standardize text.

@mld137 Discuss the map page and what you did to create the xslt

@JakeCode121 Discuss the pictures 

@dsl28 discuss the process page.

@mld137 open floor for questions and we can all answer.

Let me know if there any questions and concerns.

@Bennediction @haggis78

**Comment by haggis78** [comment]
@JakeCode121 @mld137 @dsl28 that sounds like a good plan. We look forward to hearing from you! Also, remember that there is still a project meeting time scheduled for Monday at noon. That doesn't mean that you have to have a meeting then, but I should be available during that time to help you do any debugging. Also, Dylan, I know you said you can't make the presentation time on Tuesday, so we could work out a quick video recording that can be played for your part. (Jake and Mollie, that would also mean the schedule would probably be reorganized slightly so that all of Dylan's parts can be done in one go.)
